// вместо ** название действия
export const REGISTRATION_REQUEST = "REGISTRATION_REQUEST_SUCCESS";
export const REGISTRATION_REQUEST_SUCCESS = "REGISTRATION_REQUEST_SUCCESS";
export const REGISTRATION_REQUEST_FAIL = "REGISTRATION_REQUEST_FAIL";
export const CHANGE_EVENT = "CHANGE_EVENT";



